### ISSUE TITLE
Bug Regression: Mana no longer subtracted with a skill is used.

### ISSUE THREAD

**Issue by godofgrunts** [GDquest/godot-turn-based-rpg#126] opened 2018-12-12 15:59 UTC
![mana](https://user-images.githubusercontent.com/338843/49881640-dca22580-fdfc-11e8-811b-11492f760696.gif)
Using e6bdcbb (master as of this writing)

**Comment by GresilleSiffle** [comment] 2018-12-15 16:42
I do not reproduce with the current master 79f4ba51cef21e00540943684ce1937cd1545e5d.

Do you still have the bug?

**Comment by guilhermehto** [comment] 2018-12-18 20:50
Couldn't reproduce it on d7a4376

**Comment by NathanLovato** [comment] 2018-12-18 23:15
Can't reproduce either, closing for now

**Closed by NathanLovato** 2018-12-18 23:15 UTC
